db-schema-name: tutor_db

spring:
  liquibase:
    enabled: false
  jpa:
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        #        format_sql: true
        dialect: ${spring.jpa.database-platform}
        storage_engine: innodb
        default_schema: ${db-schema-name}
    hibernate:
      ddl-auto: validate
  datasource:
    password: 1234
