db-schema-name: tutor_db

spring:
  liquibase:
    enabled: false
    change-log: db/changelog/changelog.yaml
    default-schema: ${db-schema-name}

  jpa:
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        #        format_sql: true
        dialect: ${spring.jpa.database-platform}
        storage_engine: innodb
        default_schema: ${db-schema-name}
    hibernate:
      ddl-auto: create

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tutor_db
    username: root
    password: 1234

