db-schema-name: tutor_db

spring:
  liquibase:
    enabled: false
    change-log: db/changelog/changelog.yaml
    default-schema: ${db-schema-name}

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        #        format_sql: true
        dialect: org.hibernate.dialect.MySQLInnoDBDialect
        default_schema: ${db-schema-name}
    hibernate:
      ddl-auto: create

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tutor_db
    username: root
    password: pass

