### create course
POST http://localhost:8080/courses
Content-Type: application/json

{
"periodStart": "2022-01-01",
"periodEnd": "2022-02-28",
"lessonStartTime": "11:30:00",
"lessonDuration": 45,
"dayOfWeek": "monday",
"groupId": 1
}

###

GET http://localhost:8080/courses/1
Accept: application/json

### change course
POST http://localhost:8080/courses/course
Content-Type: application/json

{
"id": 13,
"periodStart": "2022-01-05",
"periodEnd": "2022-02-28",
"lessonStartTime": "11:30:00",
"lessonDuration": 45,
"dayOfWeek": "friday",
"groupId": 1
}
###
DELETE http://localhost:8080/courses/12
