### create group
POST http://localhost:8080/groups
Content-Type: application/json

{
  "groupName": "gr2",
  "tutorId": 1
}

###
PUT http://localhost:8080/groups/addStudents
Content-Type: application/json

{
  "id": 2,
  "students": [
  7,8
  ]
}
