PUT {{url}}/students/addLessons
Content-Type: application/json

{
  "id": 1,
  "visitedLessons": [
    1,
    2
  ]
}

###
PUT {{url}}/students/{{studentId}}/lesson/{{lessonId}}

###
POST {{url}}/students
Content-Type: application/json

{
  "firstname": "student2",
  "lastname": "student2",
  "email": "student@student2.com",
  "password": "student2",
  "groupId": 1,
  "price": 2.45
}
###