PUT {{url}}/students/addLessons
Content-Type: application/json

{
  "id": 1,
  "visitedLessons": [
    37,
    38
  ]
}

###
POST {{url}}/students/getPriceByLessons
Content-Type: application/json

{
  "studentId": 1,
  "startPeriod": "2021-09-01T00:00:00",
  "endPeriod": "2021-09-30T00:00:00"
}

###
PUT {{url}}/students/{{studentId}}/lesson/{{lessonId}}

###
POST {{url}}/students
Content-Type: application/json

{
  "firstname": "student2",
  "lastname": "student2",
  "email": "student4@student2.com",
  "password": "student2",
  "groupId": 2,
  "price": 2.45
}

###
GET {{url}}/students/1

###
GET {{url}}/students

###
