### create tutor
POST http://localhost:8080/tutors
Content-Type: application/json

{
  "firstname": "tutor2",
  "lastname": "tutor2",
  "email": "tutor1@tutor2.com",
  "password": "tutor2",
  "login": "tutor2"
}

###

GET http://localhost:8080/tutors/1
Accept: application/json

###
DELETE http://localhost:8080/tutors/1
###
GET http://localhost:8080/tutors