### create tutor
POST http://localhost:8080/tutors
Content-Type: application/json

{
  "firstname": "tutor1",
  "lastname": "tutor1",
  "email": "tutor1@tutor1.com",
  "password": "tutor1"
}

###

GET http://localhost:8080/tutors/1
Accept: application/json

###